version: '3'
services:
  digitalself_webapp:
    build:
      context: .
      dockerfile: ./docker-build-files/Dockerfile
    container_name: digitalself_webapp
    volumes:
      - ./site-src-files:/usr/src/app
    depends_on:
      - digitalself_webapp_worker
    command: [ "npm", "run", "startup"]
    ports:
      - "5130:5000"
  digitalself_webapp_worker:
    build:
      context: .
      dockerfile: ./docker-build-files/DockerfileNode
    container_name: digitalself_webapp_worker
    volumes:
      - ./site-src-files:/usr/src/app
